name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    name: Publish
    if: "github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, 'chore: release v')"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun ci

      - name: Run Build
        run: bun run build

      - name: Install npm and publish to npm
        run: |
          bun i -g npm@11.18.0

          npm -v

          npm stage publish --provenance

      - name: Create Tag
        run: |
          VERSION=$(bun -p "(await import('./package.json')).version")

          git tag v$VERSION
          git push origin v$VERSION
